theme: jekyll-theme-minimal
title: Cal-DisKS
description: Calvin/Berkeley Distributed k-mer Sketcher
logo: /cal-disks-logo.png
navigation:
  - title: Home
    url: /
  - title: Source Code
    url: https://github.com/kodingkoning/sketch
  - title: Final Presentation Slides
    url: final-slides.pdf
  - title: About Me
    url: about-me
  - title: Calvin CS Department
    url: https://cs.calvin.edu
  - title: Senior Project Homepage
    url: https://cs.calvin.edu/courses/cs/396/index.html    
